##  Sharpe, Treynor & Jensen's Alpha — RELIANCE & IOC (Dec 2025 – Apr 2026)

In [1]:
import yfinance as yf
import pandas as pd

stocks = ['RELIANCE.NS', 'IOC.NS']
risk_free = 0.0625 / 252

df = yf.download(stocks, start='2025-12-01', end='2026-04-22', progress=False)['Close']
market = yf.download('^NSEI', start='2025-12-01', end='2026-04-22', progress=False)['Close']

stock_returns = df.pct_change().dropna()
market_returns = market.pct_change().dropna().squeeze()

results = {}

for stock in stock_returns.columns:
    # Building blocks
    beta = stock_returns[stock].cov(market_returns) / market_returns.var()
    avg_return = stock_returns[stock].mean()
    avg_market_return = market_returns.mean()
    std = stock_returns[stock].std()

    sharpe = (avg_return - risk_free) / std
    treynor = (avg_return - risk_free) / beta
    alpha = avg_return - (risk_free + beta * (avg_market_return - risk_free))

    results[stock] = {
        'Beta': round(beta, 4),
        'Sharpe': round(sharpe, 4),
        'Treynor': round(treynor, 4),
        'Alpha': round(alpha, 6)
    }

results_df = pd.DataFrame(results).T
print(results_df)


               Beta  Sharpe  Treynor     Alpha
IOC.NS       1.0564 -0.0377  -0.0007  0.000219
RELIANCE.NS  0.7668 -0.1166  -0.0022 -0.001030


Okay so the numbers are finally out and honestly they tell a 
really interesting story when you look at all three metrics together.

| Metric | IOC | RELIANCE |
|--------|-----|----------|
| Beta | 1.0564 | 0.7668 |
| Sharpe | -0.0377 | -0.1166 |
| Treynor | -0.0007 | -0.0022 |
| Alpha | +0.000219 | -0.001030 |

---

### Beta
IOC has a Beta of 1.05 which means it moves almost exactly 
with the Nifty 50. Makes sense — it's a government oil company 
so it's basically glued to the market.

Reliance at 0.76 is less volatile than the market. Despite being 
in oil and gas, the Jio and retail businesses cushion it from 
pure market swings. Lower beta, more stable — but as we'll see, 
stable doesn't always mean good.

---

### Sharpe Ratio
Both negative. Both stocks failed to beat the risk free rate 
of 6.25% during this period. 

Reliance at -0.1166 is actually worse than IOC at -0.0377 
which surprised me. You'd expect a more diversified company 
like Reliance to hold up better but clearly the geopolitical 
uncertainty hit it harder from a risk adjusted perspective.

---

### Treynor Ratio
Both negative again — -0.0007 for IOC and -0.0022 for Reliance.

Treynor only looks at systematic risk — the market risk you 
can't escape no matter how diversified you are. The fact that 
both are negative tells me that even the unavoidable market 
risk wasn't being compensated by returns during this crisis period.

Reliance being worse here is interesting because it has lower 
beta — meaning it took LESS market risk but still couldn't 
generate positive returns. That's quite telling.

---

### Jensen's Alpha — The Most Interesting One
This is where it gets really interesting.

IOC has a POSITIVE Alpha of +0.000219 
Reliance has a NEGATIVE Alpha of -0.001030 

What does this mean? 

IOC actually slightly OUTPERFORMED what CAPM predicted it 
should return given its Beta. It was still negative overall 
but relative to its own risk level — IOC did better than expected.

Reliance on the other hand underperformed even its own 
theoretical expected return. So not only did it give bad 
returns — it gave worse returns than its Beta predicted it would.

---

### My Overall Take 

If I had to pick between these two during the Iran-USA crisis 
based purely on these numbers — IOC was the lesser evil. 

Negative Sharpe and Treynor across the board confirms this was 
simply a terrible period to hold Indian oil stocks from a risk 
adjusted perspective. But the positive Alpha on IOC tells me 
that government backed oil marketing companies have a hidden 
resilience during geopolitical shocks — possibly because the 
government steps in to protect fuel prices and margins.

Reliance disappointing on Alpha despite lower Beta is the 
real story here. Lower risk, worse than expected returns — 
that's the worst combination you can have as an investor.

Three metrics, same conclusion — geopolitical crises punish 
Indian oil stocks hard. But not all stocks equally. And that 
difference is exactly what quant analysis helps you find. 